export type StockRow = {
  ticker: string;
  company: string;
  market: "GPW" | "USA";
  price: string;
  daily: string;
  dailyTone: "positive" | "negative" | "flat";
  status: string;
  score: string;
  nearestBuy: string;
  distance: string;
  lastMonitoring: string;
  freshness: string;
  freshnessTone: "warning" | "negative" | "muted";
};

export const stocks: StockRow[] = [
  {
    ticker: "XTB",
    company: "XTB S.A.",
    market: "GPW",
    price: "74.62 PLN",
    daily: "+1.6%",
    dailyTone: "positive",
    status: "BUY CANDIDATE",
    score: "82",
    nearestBuy: "72.00",
    distance: "3.6% above",
    lastMonitoring: "30 Aug",
    freshness: "DELAYED 15m",
    freshnessTone: "warning",
  },
  {
    ticker: "V",
    company: "Visa",
    market: "USA",
    price: "349.12 USD",
    daily: "−0.4%",
    dailyTone: "negative",
    status: "PORTFOLIO",
    score: "81",
    nearestBuy: "330.00",
    distance: "5.8% above",
    lastMonitoring: "31 Aug",
    freshness: "DELAYED 15m",
    freshnessTone: "warning",
  },
  {
    ticker: "EME",
    company: "EMCOR Group",
    market: "USA",
    price: "475.00 USD",
    daily: "+2.4%",
    dailyTone: "positive",
    status: "DEEP DIVE",
    score: "78",
    nearestBuy: "460.00",
    distance: "3.2% above",
    lastMonitoring: "28 Aug",
    freshness: "DELAYED 15m",
    freshnessTone: "warning",
  },
  {
    ticker: "PZU",
    company: "PZU S.A.",
    market: "GPW",
    price: "57.84 PLN",
    daily: "−0.7%",
    dailyTone: "negative",
    status: "WATCH",
    score: "76",
    nearestBuy: "56.00",
    distance: "3.3% above",
    lastMonitoring: "26 Aug",
    freshness: "DELAYED 15m",
    freshnessTone: "warning",
  },
  {
    ticker: "MSFT",
    company: "Microsoft",
    market: "USA",
    price: "517.40 USD",
    daily: "+0.3%",
    dailyTone: "positive",
    status: "WAIT",
    score: "74",
    nearestBuy: "495.00",
    distance: "4.5% above",
    lastMonitoring: "22 Aug",
    freshness: "DELAYED 15m",
    freshnessTone: "warning",
  },
  {
    ticker: "FIX",
    company: "Comfort Systems",
    market: "USA",
    price: "708.25 USD",
    daily: "−1.2%",
    dailyTone: "negative",
    status: "STALE REVIEW",
    score: "73",
    nearestBuy: "650.00",
    distance: "9.0% above",
    lastMonitoring: "02 Aug",
    freshness: "STALE · 2h",
    freshnessTone: "negative",
  },
  {
    ticker: "DVL",
    company: "Develia S.A.",
    market: "GPW",
    price: "7.36 PLN",
    daily: "0.0%",
    dailyTone: "flat",
    status: "WATCH",
    score: "69",
    nearestBuy: "7.10",
    distance: "3.7% above",
    lastMonitoring: "14 Aug",
    freshness: "MANUAL",
    freshnessTone: "muted",
  },
  {
    ticker: "ABE",
    company: "AB S.A.",
    market: "GPW",
    price: "—",
    daily: "—",
    dailyTone: "flat",
    status: "WAIT",
    score: "—",
    nearestBuy: "95.00",
    distance: "—",
    lastMonitoring: "Not analyzed",
    freshness: "UNAVAILABLE",
    freshnessTone: "negative",
  },
  {
    ticker: "PEP",
    company: "PepsiCo",
    market: "USA",
    price: "146.88 USD",
    daily: "+0.5%",
    dailyTone: "positive",
    status: "WATCH",
    score: "71",
    nearestBuy: "140.00",
    distance: "4.9% above",
    lastMonitoring: "20 Aug",
    freshness: "DELAYED 15m",
    freshnessTone: "warning",
  },
  {
    ticker: "CDR",
    company: "CD Projekt",
    market: "GPW",
    price: "258.40 PLN",
    daily: "+0.8%",
    dailyTone: "positive",
    status: "WAIT",
    score: "67",
    nearestBuy: "235.00",
    distance: "10.0% above",
    lastMonitoring: "18 Aug",
    freshness: "DELAYED 15m",
    freshnessTone: "warning",
  },
];

export type MonitoringRecord = {
  date: string;
  ticker: string;
  company: string;
  market: "GPW" | "USA";
  price: string;
  status: string;
  score: string;
  recommendation: string;
  summary: string;
};

export const monitoringRecords: MonitoringRecord[] = [
  {
    date: "01 Sep · 20:30",
    ticker: "EME",
    company: "EMCOR Group",
    market: "USA",
    price: "475.00",
    status: "DEEP DIVE",
    score: "78",
    recommendation: "ACCUMULATE",
    summary: "Backlog quality merits refreshed downside case.",
  },
  {
    date: "31 Aug · 18:20",
    ticker: "V",
    company: "Visa",
    market: "USA",
    price: "349.12",
    status: "PORTFOLIO",
    score: "81",
    recommendation: "HOLD",
    summary: "Payments resilience confirmed after Q3 update.",
  },
  {
    date: "30 Aug · 09:10",
    ticker: "XTB",
    company: "XTB S.A.",
    market: "GPW",
    price: "74.62",
    status: "BUY CANDIDATE",
    score: "82",
    recommendation: "ACCUMULATE",
    summary: "Valuation entered planned accumulation range.",
  },
  {
    date: "28 Aug · 21:05",
    ticker: "PZU",
    company: "PZU S.A.",
    market: "GPW",
    price: "57.84",
    status: "WATCH",
    score: "76",
    recommendation: "WATCH",
    summary: "Capital return remains attractive; wait for entry.",
  },
  {
    date: "22 Aug · 19:40",
    ticker: "MSFT",
    company: "Microsoft",
    market: "USA",
    price: "517.40",
    status: "WAIT",
    score: "74",
    recommendation: "WAIT",
    summary: "Quality intact; valuation above planned level.",
  },
  {
    date: "18 Aug · 08:15",
    ticker: "CDR",
    company: "CD Projekt",
    market: "GPW",
    price: "258.40",
    status: "WAIT",
    score: "67",
    recommendation: "WATCH",
    summary: "Pipeline visibility improved but valuation is full.",
  },
  {
    date: "14 Aug · 20:55",
    ticker: "DVL",
    company: "Develia S.A.",
    market: "GPW",
    price: "7.36",
    status: "WATCH",
    score: "69",
    recommendation: "WATCH",
    summary: "Manual price verified; thesis unchanged.",
  },
  {
    date: "02 Aug · 17:10",
    ticker: "FIX",
    company: "Comfort Systems",
    market: "USA",
    price: "708.25",
    status: "STALE REVIEW",
    score: "73",
    recommendation: "REVIEW",
    summary: "Analysis due after provider discrepancy.",
  },
  {
    date: "20 Jul · 22:05",
    ticker: "PEP",
    company: "PepsiCo",
    market: "USA",
    price: "146.88",
    status: "WATCH",
    score: "71",
    recommendation: "WATCH",
    summary: "Margin recovery offsets weak organic volume.",
  },
  {
    date: "12 Jul · 19:35",
    ticker: "EME",
    company: "EMCOR Group",
    market: "USA",
    price: "438.20",
    status: "WAIT",
    score: "74",
    recommendation: "WAIT",
    summary: "Valuation moved beyond initial entry range.",
  },
];
